global:
  scrape_interval: 15s

rule_files:
  - '/alertmanager/alert.rules'
alerting:
  alertmanagers:
    - static_configs:
      - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: 'node_exporter'
    static_configs:
      - targets: ["node_exporter:9100", "xx.xxx.xx.xx:9100"] # Kindly change the IP to any other server you have or remove it.
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']